### PR TITLE
Fix buildfarm dependency

### LINKED ISSUE #833: [Iron] Build failure on buildfarm for `webots_ros2_driver`
[Full log](https://build.ros2.org/view/Ibin_uJ64/job/Ibin_uJ64__webots_ros2_driver__ubuntu_jammy_amd64__binary/10/)

```
14:34:06 /tmp/binarydeb/ros-iron-webots-ros2-driver-2023.1.1/src/WebotsNode.cpp:17:10: fatal error: yaml-cpp/yaml.h: No such file or directory
14:34:07    17 | #include <yaml-cpp/yaml.h>
14:34:07       |          ^~~~~~~~~~~~~~~~~
14:34:07 compilation terminated.
```

The package.xml is missing a `<depend>libyaml-cpp-dev</depend>` along with a necessary includes + links in CMakeLists.txt

### PR DESCRIPTION
**Pull request by ygoumaz**
Fixes #833 

Add libyaml-cpp dependency to package.

### CODE REVIEW

**Review by BenjaminDeleze — APPROVED** [review]
Thank you

**Comment by Yadunund** [comment]
I haven't looked into the details yet but I notice that the `CMakeLists.txt` is missing a `find_package(yaml-cpp REQUIRED)` call which would be needed to link this target? https://github.com/cyberbotics/webots_ros2/blob/16efd3b06262d6a20579e486c7141c085a4f82d5/webots_ros2_driver/CMakeLists.txt#L120

**Comment by ygoumaz** [comment]
Locally it works fine without it. Is that line required?

**Comment by Yadunund** [comment]
You could try running the buildfarm job locally to see if things work before blooming a release 
https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/jobs/release_jobs.rst#run-the-release-job-locally

**Pull request merged**
