### PR TITLE
Merge `master` into `develop`

### PR DESCRIPTION
**Pull request by ad-daniel**
**Description**

Conflicts:
   - webots_ros2_driver/webots

### CODE REVIEW

**Comment by ad-daniel** [comment]
well, according to the "checks" tab the tests passed, but for some reason this pages shows as if they haven't started. Just for me?

**Comment by ygoumaz** [comment]
Same on my side. Have you tried to re-run them?

**Review by ygoumaz — APPROVED** [review]
The merge seems good to me.

**Comment by ad-daniel** [comment]
I've tried to re-run it, but I have the same behavior, not sure what's wrong with it

**Comment by ygoumaz** [comment]
This looks like a bug of Github. The same problem is happening in #498.

**Comment by ygoumaz** [comment]
The problem seems to be fixed!

**Pull request merged**
