### PR TITLE
Fix hw interface check

### PR DESCRIPTION
**Pull request by omichel**
Backport of https://github.com/cyberbotics/webots_ros2/pull/882

### CODE REVIEW

**Comment by Yadunund** [comment]
Looks like build succeeded on Rolling (main and testing) but tests are failing. Unfortunately I'm not familiar enough with the codebase to make any changes to fix tests.

**Comment by Yadunund** [comment]
Thanks @omichel! Could you bloom a new release for Rolling whenever you get a chance next?

**Comment by omichel** [comment]
I don't have time for this right now, you can do it yourself and I will be happy to help if needed. The instructions are [here](https://github.com/cyberbotics/webots_ros2/wiki/Internal-Publishing).

**Comment by Yadunund** [comment]
Hi @omichel would really appreciate your help with blooming the release. I'm not sure how the version increases work in this project. Further i won't be able to run `bloom` as I don't have the required access within [ros2-gbp](https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/cyberbotics.tf)

**Comment by omichel** [comment]
I just proposed to add you [here](https://github.com/ros2-gbp/ros2-gbp-github-org/pull/437). Hopefully, this will be accepted and merged soon.
The version numbering is based on the Webots version.
The current version is version='2023.1.1', where '2023.1' matches with the Webots version, e.g., R2023b ('2023.0' means Webots R2023a) and the final '.1' means first release of the ROS 2 interface for Webots R2023b. Thus, if you want to make new release, the version should be increased to '2023.1.2' to mean it aims at Webots R2023a and is version 2.

**Pull request merged**
