### PR TITLE
Upgrade to Webots R2021b

### PR DESCRIPTION
**Pull request by lukicdarkoo**
This PR follows the release of Webots R2021b.

Since we are constantly getting `Can’t automatically merge` (e.g. #229, #230, and #231), I prefer to create a new `develop` branch. Therefore, I created a new branch (`feature-r2021b-upgrade`) out of the `master` branch and manually applied changes from the `develop` branch.

**Changes**:
- [x] fix the webots_ros2_demos example, avoid `Error: wb_motor_set_position() called with an invalid 'position' argument (NaN).`
- [x] fix the Mavic example, avoid `wb_gps_get_values() called for a disabled device! Please use: wb_gps_enable().`
- [x] upgrade urdf2webots 

**Verify**:
- [x] ros2 launch webots_ros2_demos armed_robots.launch.py
- [x] ros2 launch webots_ros2_universal_robot universal_robot_rviz_dynamic.launch.py
- [x] webots_ros2_examples
- [x] webots_ros2_tiago
- [x] webots_ros2_abb
- [x] webots_ros2_tesla
- [x] webots_ros2_mavic

### CODE REVIEW

**Review by BenjaminDeleze — APPROVED** [review]
Thank you!

**Comment by stefaniapedrazzi** [comment]
Shouldn't this branch only contain changes in the Webots version w.r.t the develop branch?

Here are the files containing changes unrelated  to the version:
* armed_robots_ur.py
* CMakeLists.txt
* README.txt
* mavic_driver.py
* robot_launch.py

Is it correct?
Why these changes have not been applied directly on the develop branch?

**Comment by lukicdarkoo** [comment]
> Here are the files containing changes unrelated to the version:
> 
> * armed_robots_ur.py
> * CMakeLists.txt
> * README.txt
> * mavic_driver.py
> * robot_launch.py

The develop branch wasn't fully functional, so the PR fixes it. The changes are mentioned in the PR description.

**Comment by stefaniapedrazzi** [comment]
I see. These files were not changed in the develop branch but in the master branch.

**Pull request merged**
