### PR TITLE
Update URDF loading to include default robot configuration in Ros2Control

### PR DESCRIPTION
**Pull request by skpawar1305**
**Description**
For the latest ros2_control update we face 
[webots_controller_SpotArm-6] terminate called after throwing an instance of 'std::runtime_error'
[webots_controller_SpotArm-6]   what():  Hardware name WebotsControl is duplicated. Please provide a unique 'name' in the URDF. for humble

**Affected Packages**
List of affected packages:
  - webots_ros2_control

**Additional context**
load_urdf is called only to set is_urdf_loaded__ = true

### CODE REVIEW

**Comment by lukicdarkoo** [comment]
@skpawar1305 Can you confirm the error occurred on Humble main (not testing) and Webots R2023b? Or it is some other version?

**Comment by lukicdarkoo** [comment]
@skpawar1305 I managed to reproduce the error in our test examples. With the latest ros2_control for Humble (compiled from source) there is no error. I believe the issue is related:
https://github.com/ros-controls/ros2_control/pull/1960

Given `load_urdf` is called with:
- validate_interfaces = false
- load_and_initialize_components = false
the error should not appear.

**Comment by skpawar1305** [comment]
okay, I'll delete this branch later then. thank you

**Comment by lukicdarkoo** [comment]
@skpawar1305 Here is a hotfix until the Humble sync:
```bash
# HOTFIX: https://github.com/ros-controls/ros2_control/pull/1960
wget -O /tmp/hotfix.deb http://snapshots.ros.org/humble/2024-08-28/ubuntu/pool/main/r/ros-humble-hardware-interface/ros-humble-hardware-interface_2.43.0-1jammy.20240823.145349_amd64.deb && \
    sudo apt install -y --allow-downgrades /tmp/hotfix.deb && \
    rm -f /tmp/hotfix.deb
```
It will install a slightly older version of `resource_manager`.

**Pull request closed without merging**
