### PR TITLE
set is_urdf_loaded__ of the resource manager to true

### PR DESCRIPTION
**Pull request by skpawar1305**
it's probably needed after https://github.com/ros-controls/ros2_control/commit/385293e5d0626c57636a05c66de4380fcfd5bee7

fixes https://github.com/cyberbotics/webots_ros2/issues/893

**Description**
After, https://github.com/ros-controls/ros2_control/commit/385293e5d0626c57636a05c66de4380fcfd5bee7, init_services() won't be called unless is_urdf_loaded__ is set to true. Passing robot description again led to controller name duplicate error.

**Related Issues**
This pull-request fixes issue https://github.com/cyberbotics/webots_ros2/issues/893

**Affected Packages**
List of affected packages:
  - webots_ros2_control

**Tasks**
Add the list of tasks of this PR.
  - [x] Fix ros2_control usage for ros2 humble

### CODE REVIEW

**Comment by omichel** [comment]
Thank you. That seems to fix the problem indeed. The ROS2 tests are now passing on humble (main)!

**Review by omichel — APPROVED** [review]

**Comment by elad-eyal** [comment]
noob question if you will, @omichel  - how long until `sudo apt  ros-humble-ros2-control` on Ubuntu 22.04  takes the version with this change? (or actually, how could tell that that version should be working?). thanks

**Comment by omichel** [comment]
I don't have time for this, but @Yadunund was planning to bloom a release, see #883.

**Comment by Yadunund** [comment]
> I don't have time for this, but @Yadunund was planning to bloom a release, see #883.

The release is blocked by several test failures on `master` which need to be resolved first. See https://github.com/cyberbotics/webots_ros2/pull/892#issuecomment-1926633006

**Pull request merged**
