### PR TITLE
Renan/webots ros2 cpp

### PR DESCRIPTION
**Pull request by renan028**
**Description**
Webots-ROS2 Cpp interface
It requires a lot of sensors and controllers integration yet, but it is a starting point.
It needs an example (launch file with the `wb_task_node`).
And a minimal diff_driver_controller (ros2_control integration?).
Please feel free to improve.

In the core, It adds a launch file to just launch webots simulator without controllers (because that would be a job for the cpp node).

**Affected Packages**
List of affected packages:
  - webots_ros2_core

### CODE REVIEW

**Comment by lukicdarkoo** [comment]
Very nice! Thank you for this initiative!

> And a minimal diff_driver_controller (ros2_control integration?).

Yes, we want to do everything through `ros2_control`. Even sensors such as IMU should be integrated through `ros2_control`.

What is your motivation behind this? We have been considering moving everything to C++ because of `ros2_control` (see https://github.com/cyberbotics/webots_ros2/issues/210). However, Python is a very friendly way to extend a driver. Ideally, we would keep both interfaces (C++ and Python).

This is a very big change (most probably needed one). Therefore, we have to understand challenges quite well and tailor the design carefully.

We should keep the following in mind:
- https://github.com/cyberbotics/webots_ros2/issues/210: As stated in the issue, we want to get rid of the custom-made controllers in favor of the controllers from `ros2_control`.
- https://github.com/cyberbotics/urdf2webots/issues/112: All configurations that are currently done through ROS parameters (e.g. https://github.com/cyberbotics/webots_ros2/blob/d0f772b358252cda6b9e56768e5ec5cf7454a5ff/webots_ros2_core/webots_ros2_core/devices/sensor_device.py#L34-L38) should live in the `<webots>` tag.
- The C++ interface should be easily expandable with C++ and Python.

**Comment by renan028** [comment]
I was the main contributor of the [Miron-Project](https://github.com/MiRON-project), which uses Webots simulator and ROS1 to test some academic research (mainly contextual navigation).
My last contribution to the project was the [tiago_webot_ros](https://github.com/MiRON-project/tiago_webots_ros), a package that integrates the Tiago robot (Pal Robotics) in Webots with the ROS1 Navigation Package.  

The project ended in 2020. In my spare time, I started to learn ROS2 and to integrate Navigation2 (ROS2) on the same [Tiago project](https://github.com/renan028/tiago_webots_ros2). My goal was to accomplish the same results with ROS2. I manage to integrate everything with the webots_ros2 python package, but I am getting huge offsets in localization and problems to set goals sometimes (I think ROS2/Navigation2 is not stable yet or maybe the problem is mixing python with C++ ? I have to debug). 

Currently, I am working with Gazebo at work, but I like to explore other simulators in my spare time. I had a nice experience with Webots before, I like the webots_ros API and I think webots_ros2 is a nice start to play with ROS2. And, I will probably try multi-robot soon on webots ROS1, because I am not happy with Gazebo for this particular purpose. 

I will take a look at the ros2_control and the other links you shared, in my spare time, and share with you my thoughts on this integration. But, as you said, this is a big change and it requires a well thought (software architect) design. This draft is currently only a ROS2-cpp version of some sensors (not IMU, which should be in ros2_control).

**Comment by lukicdarkoo** [comment]
> My last contribution to the project was the tiago_webot_ros, a package that integrates the Tiago robot (Pal Robotics) in Webots with the ROS1 Navigation Package.

Nice project!

> but I am getting huge offsets in localization and problems to set goals sometimes

Maybe the odometry is not correct, like wheel separation or wheel radius, or there is some bug in sampling? Anyhow, `ros2_control` should resolve it.

> I will take a look at the ros2_control and the other links you shared, in my spare time, and share with you my thoughts on this integration. But, as you said, this is a big change and it requires a well thought (software architect) design. 

We can have a video call to discuss the new design :) I will try to specify some design ideas before.

**Comment by renan028** [comment]
> We can have a video call to discuss the new design :) I will try to specify some design ideas before.
That would be great. Feel free to add me to a channel where we can discuss it.

**Comment by lukicdarkoo** [comment]
Implemented in #221

**Pull request closed without merging**
