### PR TITLE
Improve Tiago navigation

### PR DESCRIPTION
**Pull request by ygoumaz**
RViz and the navigation must be started once the Webots simulation is ready to avoid a lot of warnings in the terminal.

Also the test should publish the initial position only when a subscriber is ready. In addition, the current succeeding condition of the test is wrong and should be `< -2.0` for the robot to move a few seconds towards the given goal position.

The TIAGo test is skipped, because the Navigation 2 package is outdated and is not working with the given configuration.

### CODE REVIEW

**Comment by ygoumaz** [comment]
The PR is (finally) ready for review!

**Comment by ygoumaz** [comment]
Back to draft...

**Review by ad-daniel — APPROVED** [review]
Thank you. By the way I still have a doubt concerning whether the CI is actually working, the timings seem correct but the summary line at the end now shows 
`Summary: 436 tests, 0 errors, 0 failures, 127 skipped`
If you go back like 2 months in the test suite, there weren't as many being skipped. Do you have any idea why?

**Review by ad-daniel — APPROVED** [review]

**Comment by ygoumaz** [comment]
I think this is normal because in addition to our tests, there is also other tests performed from other ament packages. I believe they added more tests in these packages in the last weeks. These updates may even be a reason why CI industrial was not working properly a few days ago. 

If we check the logs in detail, we see that our tests succeed and are skipped when needed (turtlebot for example).

**Comment by ad-daniel** [comment]
Those I saw had significantly less skipped, for instance [this](https://github.com/cyberbotics/webots_ros2/actions/runs/3898617271/jobs/6657517130) from January 12th 
```
Summary: 457 tests, 0 errors, 0 failures, 3 skipped
```

**Comment by ygoumaz** [comment]
In fact, the high number of tests skipped is only on Humble. On Foxy, less tests are skipped. But this seems consistent between the test you mention and two ones from today.

**Pull request merged**
