### PR TITLE
Delete the `controller_manager` timeout workaround

### PR DESCRIPTION
**Pull request by lukicdarkoo**
- [x] Check whether the workaround occurs somewhere else

### CODE REVIEW

**Comment by BenjaminHug8** [comment]
It seems that `turtlebot3` system tests fail time to time...

**Comment by lukicdarkoo** [comment]
I thought the test issue is related to?
https://github.com/cyberbotics/webots_ros2/pull/340#issuecomment-970298577

**Comment by BenjaminHug8** [comment]
> I thought the CI issue is related to? [#340 (comment)](https://github.com/cyberbotics/webots_ros2/pull/340#issuecomment-970298577)

Yes you are right, I forgot this sorry.

**Review by BenjaminHug8 — APPROVED** [review]
Thank you.

**Pull request merged**
