### PR TITLE
Update calculation of `CameraRecognitionObject`

### PR DESCRIPTION
**Pull request by AKreutz**
Calculation now conforms to the new camera coordinate frame introduced with Webots R2022b.

Signed-off-by: Andreas Kreutz <andreas.kreutz@hotmail.de>

**Description**
With the release of Webots R2022b, the coordinate frame for cameras has been changed. This means that the calculation of `CameraRecognitionObject` messages needs to be updated. 

**Related Issues**
This pull-request fixes issue #517 

**Affected Packages**
List of affected packages:
  - webots_ros2_driver
  - webots_ros2_tests

### CODE REVIEW

**Comment by ygoumaz** [comment]
Thanks a lot for your contribution! The tests are failing because of a format error (flake8), see https://github.com/cyberbotics/webots_ros2/actions/runs/3489385924/jobs/5839989049#step:3:7108 and following lines.

Could you also please add a line in the CHANGELOG files ([webots_ros2/CHANGELOG.rst](https://github.com/cyberbotics/webots_ros2/blob/master/webots_ros2/CHANGELOG.rst), [webots_ros2_driver/CHANGELOG.rst](https://github.com/cyberbotics/webots_ros2/blob/master/webots_ros2_driver/CHANGELOG.rst), [webots_ros2_tests/CHANGELOG.rst](https://github.com/cyberbotics/webots_ros2/blob/master/webots_ros2_tests/CHANGELOG.rst))?

**Review by ygoumaz — APPROVED** [review]
Thank you!

**Comment by omichel** [comment]
@AKreutz: I sent you an invite to become a member of the webots committers group which would allow you to create branches and PRs on our repositories, as well as merge your PRs.

**Comment by AKreutz** [comment]
Thanks for the quick review and the invite!

**Pull request merged**
