### PR TITLE
Set Bloom release Package

### PR DESCRIPTION
**Pull request by DavidMansolino**
**Description**

The upmost package is `webots_ros2_desktop` and not the default one )from the repo name `webots_ros2`).

### CODE REVIEW

**Comment by DavidMansolino** [comment]
It is still failing because for some reason it is still pointing to `https://github.com/omichel/webots_ros2.git` instead of `https://github.com/cyberbotics/webots_ros2.git` and therefore is not seeing the new 0.0.4 tag.

**Comment by DavidMansolino** [comment]
It looks now correctly into 'https://github.com/cyberbotics/webots_ros2.git' but still refers to 0.0.3

**Comment by DavidMansolino** [comment]
It is definitely using Release 0.0.3 for creating the release :-/
I have the same issue when creating manually the release on my computer, I have to explicitly update the version (which is not possible from the Github action).

**Comment by DavidMansolino** [comment]
Since this workflow is not working and can be confusing, it is probably better to remove it.

**Review by lukicdarkoo — APPROVED** [review]
Thanks!

**Pull request merged**
