### PR TITLE
Fix webots_ros2_importer

### PR DESCRIPTION
**Pull request by DavidMansolino**
**Description**
This package is having several issues.

### CODE REVIEW

**Comment by lukicdarkoo** [comment]
It is not the prettiest solution, but it works :)

**Comment by DavidMansolino** [comment]
> It is not the prettiest solution, but it works :)

But pep8 doesn't like it :laughing: 
https://travis-ci.com/github/cyberbotics/webots_ros2/jobs/402037530#L1409

We probably have to ignore `E402` in the pep8 test of this module.

**Comment by lukicdarkoo** [comment]
I didn't know we can ignore errors in comments (e.g. `# noqa: E402`). It's a much better solution than creating a custom config file.

**Review by DavidMansolino — COMMENTED** [review]
Thank you.
I approve this PR  (I can't formally approve since I am the original author).

**Review by lukicdarkoo — APPROVED** [review]
I approved it :)

**Pull request merged**
