### PR TITLE
Bump version and changelogs to 2023.1.2

### PR DESCRIPTION
**Pull request by Yadunund**
Once this is merged, I can tag master as `2023.1.2` and bloom a new release into Rolling to unblock the sync.

> Note: There were over 10 commits between the last released version and `master` so hoping there are no new regressions 🤞🏼

### CODE REVIEW

**Review by omichel — APPROVED** [review]

**Comment by omichel** [comment]
Unfortunately, the required ROS2 tests / industrial_ci (main, humble) is failing consistently, although the same test passes on rolling, but (not iron). Can you look into it?

**Comment by Yadunund** [comment]
Hi @omichel ,

I don't think changes in this PR could cause new CI failures so the failures must have come via previously merged commits? The CI failures are due to tests failings.
```bash
2024-02-02T13:54:51.6761473Z ======================================================================
2024-02-02T13:54:51.6761741Z FAIL: testMovement (test_system_tiago.TestTiago)
2024-02-02T13:54:51.6762117Z ----------------------------------------------------------------------
2024-02-02T13:54:51.6762317Z Traceback (most recent call last):
2024-02-02T13:54:51.6763006Z   File "/root/target_ws/src/webots_ros2/webots_ros2_tests/test/test_system_tiago.py", line 90, in testMovement
2024-02-02T13:54:51.6763765Z     self.wait_for_messages(self.__node, Odometry, '/odom', condition=on_message_received, timeout=60*5)
2024-02-02T13:54:51.6764510Z   File "/root/target_ws/src/webots_ros2/webots_ros2_tests/webots_ros2_tests/utils.py", line 56, in wait_for_messages
2024-02-02T13:54:51.6765416Z     self.assertGreaterEqual(len(received_messages), messages_to_receive, 'Not enough messages have been received')
2024-02-02T13:54:51.6765981Z AssertionError: 0 not greater than or equal to 1 : Not enough messages have been received
```

I'm simply trying to get Rolling unblocked and don't have the bandwidth to fix any tests here . If it's okay with you I'd like to suggest the following:
1. We create a new `rolling` branch off the last know release tag `2023.1.1`.
2. I cherry pick the fix for rolling into this branch and tag the latest release `2023.1.2`
3. Update the [tracks.yaml](https://github.com/ros2-gbp/webots_ros2-release/blob/bd3da1044f9229cfd73a6fb9b1607be82c6e84d9/tracks.yaml#L174) such that we bloom into Rolling from this new `rolling` branch. Currently it is set to `master.`
4. Bloom the patch fix from `rolling` branch.

We are actively working on migrating Rolling to Ubuntu 24.04 and the next Rolling sync is planned for 6th Feb as mentioned here https://discourse.ros.org/t/preparing-for-rolling-sync-2024-02-06/35882
If the issue is not resolved by then, these packages will be removed from the Buildfarm for Rolling.

**Comment by omichel** [comment]
I am fine with your proposal. You can go ahead.

**Comment by Yadunund** [comment]
See https://github.com/cyberbotics/webots_ros2/pull/892#issuecomment-1926633006

**Pull request closed without merging**
