### PR TITLE
Fix version check for hardware_interface

### LINKED ISSUE #881: Build Issues on ROS 2 Buildfarm for Rolling
Rolling binary jobs have been failing: https://build.ros2.org/view/Rbin_uJ64/job/Rbin_uJ64__webots_ros2_control__ubuntu_jammy_amd64__binary/233/console

Specifically with the error

```bash
15:07:43 /tmp/binarydeb/ros-rolling-webots-ros2-control-2023.1.1/src/Ros2Control.cpp:86:59: error: ‘__gnu_cxx::__alloc_traits<std::allocator<hardware_interface::HardwareInfo>, hardware_interface::HardwareInfo>::value_type’ {aka ‘struct hardware_interface::HardwareInfo’} has no member named ‘hardware_class_type’
15:07:43    86 |       const std::string hardwareType = controlHardware[i].hardware_class_type;
15:07:43       |                                                           ^~~~~~~~~~~~~~~~~~~
15:07:43 /tmp/binarydeb/ros-rolling-webots-ros2-control-2023.1.1/src/Ros2Control.cpp:101:24: error: ‘class hardware_interface::ResourceManager’ has no member named ‘activate_all_components’
15:07:43   101 |       resourceManager->activate_all_components();
15:07:43       |                        ^~~~~~~~~~~~~~~~~~~~~~~
15:07:43 make[4]: *** [CMakeFiles/webots_ros2_control.dir/build.make:79: CMakeFiles/webots_ros2_control.dir/src/Ros2Control.cpp.o] Error 1
```

Likely because `hardware_interface` was bumped to major version `4` on Rolling and hence [control flow here goes wrong](https://github.com/cyberbotics/webots_ros2/blob/b65c5aea7fc203b25125b96c918f7624aa2002c4/webots_ros2_control/src/Ros2Control.cpp#L81).

As a result we are unable to perform a sync for Rolling.

### PR DESCRIPTION
**Pull request by Yadunund**
Fix #881 

Latest version of `hardware_interface` on Rolling is `4.2.0`

### CODE REVIEW

**Comment by Yadunund** [comment]
cc: @omichel

**Comment by omichel** [comment]
I moved your PR to #883 (on this repository), so that we can perform the CI tests.

**Comment by Yadunund** [comment]
Thanks for the quick follow up! Really appreciate it!

**Comment by omichel** [comment]
By the way, I sent you an invite to become a member of the webots-committers group, so that you will be able to create branches and PRs on this repository for which the CI test can run.

**Comment by Yadunund** [comment]
> By the way, I sent you an invite to become a member of the webots-committers group, so that you will be able to create branches and PRs on this repository for which the CI test can run.

Got it, thanks!

**Pull request merged**
