### PR TITLE
Update Tests to Foxy

### PR DESCRIPTION
**Pull request by DavidMansolino**
**Description**
This PR removes the test on Dashin (we decided to not support it anymore) and add tests for Foxy instead.

### CODE REVIEW

**Comment by DavidMansolino** [comment]
Currently, the following package are broken because of dependencies not available on Foxy:
  - webots_ros2_epuck: missing `navigation2`
  - webots_ros2_importer: missing `xacro`

**Comment by lukicdarkoo** [comment]
`xacro` is available on my PC now:
```
lukic@ltp:~$ apt-cache search xacro foxy
ros-foxy-xacro - Xacro (XML Macros) Xacro is an XML macro language.
```

`navigation2` will become optional dependency once #86 is merged

**Comment by DavidMansolino** [comment]
You're right I restarted the tests and now only the ``navigation2`` package is missing. Can I ask you to backport the ``navigation2`` fix on master too so that we can do a release for foxy soon?

**Comment by lukicdarkoo** [comment]
Sure, I will do it now.

**Comment by DavidMansolino** [comment]
Thank you.
Feel free to do it directly on this PR if you want so that the test runs on foxy too.

**Pull request merged**
