### PR TITLE
bump python version to 3.10 for rolling

### PR DESCRIPTION
**Pull request by ijnek**
**Description**
Use Python 3.10 for Rolling on Ubuntu Jammy to fix current CI failure.
**This requires the auto-generated python310 directory in https://github.com/cyberbotics/webots-libcontroller/tree/R2022b/lib/linux-gnu before being merged**, (related to https://github.com/cyberbotics/webots/pull/4474)

Current error log when compiling on Ubuntu Jammy:
```
--- stderr: webots_ros2_driver
  CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
    (Required is exact version "3.8")
  Call Stack (most recent call first):
    /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
    /usr/share/cmake-3.22/Modules/FindPythonLibs.cmake:310 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
    CMakeLists.txt:20 (find_package)
  
  
  ---
```

**Related Issues**
No related issue

**Affected Packages**
List of affected packages:
  - webots_ros2_driver

### CODE REVIEW

**Comment by lukicdarkoo** [comment]
There should be a condition to decide whether to use Python 3.10 or 3.8 depending on the ROS distribution.

Also, the Webots libController is not compiled with Python 3.10:
https://github.com/cyberbotics/webots-libcontroller/tree/R2022a/lib/linux-gnu

This should probably be solved in the Webots main repo.

**Comment by ad-daniel** [comment]
On Webots side, support for 3.10 is being added here: https://github.com/cyberbotics/webots/pull/4474

**Comment by ijnek** [comment]
@lukicdarkoo @ad-daniel Thank you for reviewing!

> There should be a condition to decide whether to use Python 3.10 or 3.8 depending on the ROS distribution.

May I ask what branching strategy you use with your releases for webots_ros2? I assumed that you use the foxy and galactic branches for each of the distros, and merging this into master would not affect other distros than rolling (in which then it shouldn't be an issue because rolling targets Ubuntu Jammy as tier 1 - which uses python3.10).

I see in rosdistro that you're [using the ``master`` branch for the galactic releases](https://github.com/ros/rosdistro/blob/492ca1db88651a26941ee6545276a0bb6fedfd89/galactic/distribution.yaml#L5808).

I also see a ``rolling`` branch in this repository which is behind ``master``, what's that branch?

I am happy to make changes where appropriate.

**Comment by omichel** [comment]
> May I ask what branching strategy you use with your releases for webots_ros2? I assumed that you use the foxy and galactic branches for each of the distros, and merging this into master would not affect other distros than rolling (in which then it shouldn't be an issue because rolling targets Ubuntu Jammy as tier 1 - which uses python3.10).
> 
> I see in rosdistro that you're [using the `master` branch for the galactic releases](https://github.com/ros/rosdistro/blob/492ca1db88651a26941ee6545276a0bb6fedfd89/galactic/distribution.yaml#L5808).
> 
> I also see a `rolling` branch in this repository which is behind `master`, what's that branch?
> 
> I am happy to make changes where appropriate.

Actually, we don't use any more the foxy/galactic/rolling branches, we are going to delete them soon. The code on the master branch is common to all ROS 2 distributions, see details [here](https://github.com/cyberbotics/webots_ros2/pull/433#issuecomment-1109599199).

**Review by omichel — APPROVED** [review]
Looks good to me.

**Pull request merged**
