### PR TITLE
Remove double `webots_ros2_driver` header installation

### LINKED ISSUE #282: webots_ros2_driver include directory is installed twice
The following two directories have same contents.
   ~\install\include\webots_ros2_driver
   ~\install\include\webots_ros2_driver\webots_ros2_driver

The line137~140 are neither necessary nor useful in ~\webots_ros2_driver\CMakeLists.txt.
install(
 DIRECTORY include/${PROJECT_NAME}
 DESTINATION include/${PROJECT_NAME}
)

### PR DESCRIPTION
**Pull request by lukicdarkoo**
Fixes #282

### CODE REVIEW

**Review by BenjaminHug8 — APPROVED** [review]
Thank you!

**Comment by lukicdarkoo** [comment]
> I think it would be great if we could get rid of the few fails we get when tests use RViz

The TurtleBot example is in the ROS 2 documentation, we need to test it. Maybe, we can reach out to Robotis to add a parameter `use_rviz`, so we can disable RViz.

**Comment by lukicdarkoo** [comment]
@BenjaminHug8 I suggested them the change:
https://github.com/ROBOTIS-GIT/turtlebot3/pull/799

**Comment by BenjaminHug8** [comment]
Perfect thank you!

**Comment by omichel** [comment]
> 
> 
> @BenjaminHug8 I suggested them the change: [ROBOTIS-GIT/turtlebot3#799](https://github.com/ROBOTIS-GIT/turtlebot3/pull/799)

Already merged!

**Pull request merged**
